# Generated by Django 4.1.2 on 2023-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manana', '0002_outs_ubicacion_alter_outs_code_alter_outs_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='outs',
            name='puertas',
            field=models.CharField(choices=[('', 'Seleccione una opción'), ('Puerta1', 'P1'), ('Puerta2', 'P2'), ('Puerta3', 'P3')], default='', max_length=10),
        ),
    ]
