# Generated by Django 4.1.2 on 2023-07-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manana', '0003_outs_puertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='outs',
            name='motivos',
            field=models.CharField(choices=[('', 'Seleccione motivo'), ('Llenado', 'LLenado'), ('Picking', 'Picking'), ('PlanB', 'PlanB'), ('Guardia', 'Guardia')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='outs',
            name='puertas',
            field=models.CharField(choices=[('', 'Seleccione puerta'), ('Puerta1', 'P1'), ('Puerta2', 'P2'), ('Puerta3', 'P3'), ('Plataforma', 'Plataforma')], default='', max_length=10),
        ),
    ]
