# Generated by Django 4.1.2 on 2023-07-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manana', '0004_outs_motivos_alter_outs_puertas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outs',
            old_name='motivos',
            new_name='motivo',
        ),
    ]
