# Generated by Django 4.1.2 on 2023-07-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manana', '0005_rename_motivos_outs_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outs',
            name='code',
            field=models.CharField(max_length=8, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='outs',
            name='ubicacion',
            field=models.CharField(max_length=6, null=True, verbose_name='Ubicacion'),
        ),
    ]
