# Generated by Django 4.1.2 on 2023-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manana', '0006_alter_outs_code_alter_outs_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='outs',
            name='hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora'),
        ),
    ]
